### ISSUE TITLE
Typo in absmarly.py filename

### ISSUE THREAD

**Issue by reallyrehan** [absmartly/python3-sdk#4]
There is a typo in the main absmarly.py filename. Not a big issue but it creates confusion between the filename and the classname when importing.

Filename => [absmarly.py](https://github.com/absmartly/python3-sdk/blob/main/sdk/absmarly.py)
Class name => [AbSmartly](https://github.com/absmartly/python3-sdk/blob/6f896b6a60c4b0f21176cdead592547c0eb98e7a/sdk/absmarly.py#L16)

**Comment by bmsilva** [comment]
I've only changed the name of the module, the class name I left as is to be consistent with documentation and other classes (e.g.: ABSmartlyConfig).

**Comment by reallyrehan** [comment]
Great, thanks for the quick fix!
